<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Executor</AssemblyName>
    <RootNamespace>Executor</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>executor.ico</ApplicationIcon>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <!--
    To publish as a single, self-contained EXE (no .NET runtime required):
      dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true
  -->

</Project>
